#pragma once
#define OGRE_STACK_UNWINDING	1
#define OGRE_RELEASE_ASSET		0
#define OGRE_TEST_MULTIPASS		0
#define OGRE_DOUBLE_PRECISION	0
#define	OGRE_WCHAR_T_STRINGS	0
#define OGRE_MAX_TEXTURE_COORD_SETS	6
#define OGRE_MAX_TEXTURE_LAYERS	8
#define OGRE_DYNAMIC_LAYERS		8
#define OGRE_DYNAMIC_LINKAGE	1
#define OGRE_DEBUG_MEMORY_MANAGER	1

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
